### ISSUE TITLE
Print does not work, while JsonConvert.SerializeObject works fine

### ISSUE THREAD

**Issue by Freymaurer** [CSBiology/DynamicObj#13]
I have a nested dynamic object type:

```fsharp
let response =
    [
        "StatusCode", string result.Value.Response.StatusCode
        "Time", (System.DateTime.Now.ToUniversalTime() - st).ToString()
    ]
    |> List.map (fun x -> fst x, snd x |> Some)
let request =
    let query =
        let queryLogger = Logger()
        ctx.Request.Query |> Seq.iter (fun x -> queryLogger.setProp(x.Key, Some x.Value) )
        queryLogger
    let headers =
        let queryLogger = Logger()
        ctx.Request.Headers |> Seq.iter (fun x -> queryLogger.setProp(x.Key, x.Value |> String.concat "," |> Some ) )
        queryLogger 
    let userAgent =
        ctx.Request.Headers
        |> Seq.tryFind (fun x -> x.Key ="User-Agent")
        |> Option.map (fun x -> x.Value |> String.concat ",")
        |> Option.defaultValue ""
    let contentType =
        ctx.Request.Headers
        |> Seq.tryFind (fun x -> x.Key ="Content-Type")
        |> Option.map (fun x -> x.Value |> String.concat ",")
        |> Option.defaultValue ""
    [
        "Path", box ctx.Request.Path
        "PathBase", box ctx.Request.PathBase
        "Method", box ctx.Request.Method
        "Host", box ctx.Request.Host.Host
        "Port",
            if ctx.Request.Host.Port.HasValue then string ctx.Request.Host.Port.Value else ""
            |> box
        "QueryString",
            if ctx.Request.QueryString.HasValue then string ctx.Request.Host.Port.Value else ""
            |> box
        "Query", if ctx.Request.Query.Count > 0 then box query else null
        "Headers", if ctx.Request.Headers.Count > 0 then box headers else null
        "UserAgent", box userAgent
        "ContentType", box contentType
    ]
    |> List.map (fun x -> fst x, snd x |> Some)
let logger =
    let props =
        [
            "Timestamp", st.ToString("yyyy.MM.dd hh:mm:ss.fffff") |> box
            "Request", Logger.init(request) |> box
            "Response", Logger.init(response) |> box
        ]
        |> List.map (fun x -> fst x, snd x |> Some)
    Logger.init(props)
```

The json export works:
```fsharp
logger |> JsonConvert.SerializeObject |> printfn "%A"
```

```json
{
    "Timestamp": "2022.03.25 12:53:37.89496",
    "Request": {
      "Path": "/api/IHelpdeskAPI/getCaptcha",
      "PathBase": "",
      "Method": "GET",
      "Host": "localhost",
      "Port": "8085",
      "QueryString": "",
      "Query": null,
      "Headers": {
        "Connection": "close",
        "Content-Type": "application/json; charset=utf-8",
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate, br",
        "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
        "Cookie": "ajs_anonymous_id=%22bf0866e7-3877-4d25-8805-c1b2a4b5bd71%22; isDarkmode=false",
        "Host": "localhost:8085",
        "Referer": "http://localhost:8080/?topic=Tools_Swate",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36 OPR/84.0.4316.42",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin",
        "sec-ch-ua-platform": "\"Windows\"",
        "sec-ch-ua-mobile": "?0",
        "x-remoting-proxy": "true",
        "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"98\", \"Opera\";v=\"84\""
      },
      "UserAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36 OPR/84.0.4316.42",
      "ContentType": "application/json; charset=utf-8"
    },
    "Response": {
      "StatusCode": "200",
      "Time": "00:00:24.8929431"
    }
  }
```

But `DynObj.print logger` returns an error:

```bash
System.MemberAccessException: Cannot access member.
  at DynamicObj.DynamicObj.op_Dynamic[b](b lookup, String name)
  at DynamicObj.DynObj.loop@93-3(DynamicObj d, DynamicObj object, Int32 identationLevel, FSharpList`1 membersLeft, FSharpList`1 acc)
  at DynamicObj.DynObj.loop@93-3(DynamicObj d, DynamicObj object, Int32 identationLevel, FSharpList`1 membersLeft, FSharpList`1 acc)
  at System.Runtime.CompilerServices.RuntimeHelpers.DispatchTailCalls(IntPtr callersRetAddrSlot, IntPtr callTarget, IntPtr retVal)
  at DynamicObj.DynObj.format(DynamicObj d)
  at DynamicObj.DynObj.print(DynamicObj d)
```

**Comment by Freymaurer** [comment]
This will be fixed with PR #15.
